# this docker file builds a native image of the application and deploys it in a docker container
# 
# docker build -t spring/foodtracker-spring-jvm .
#
# to run:
# docker run -i --rm -p 8081:8081 spring/foodtracker-spring-jvm


FROM openjdk:11.0.7-jdk

COPY target/food-tracker-springboot-1.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]
